### ISSUE TITLE
消息的合法性校验方式变了

### ISSUE THREAD

**Issue by ulyn** [ineo6/hubot-dingtalk#3]
钉钉的机器人数据校验方式已经变了 不是token了。要升级一下？
文档 https://ding-doc.dingtalk.com/doc#/serverapi2/elzz1p

**Comment by ineo6** [comment]
是的，感谢提醒，近期会更新的。

**Comment by ineo6** [comment]
已更新代码支持`token`和`sign`两种方式，`sign`签名方式属于企业内部机器人才会有的，自测自定义机器人还是通过`token`方式。
