### ISSUE TITLE
钉钉内部机器人发送内容无应答

### ISSUE THREAD

**Issue by Chillimeat** [ineo6/hubot-dingtalk#5]
你好，
我添加的是钉钉企业内部机器人，添加完成之后，hubot-dingtalk跑起来了，但是在群里@机器人 不会回复呀，我已经在脚本里面加了简单的应答了。

**Comment by ainuoyan** [comment]
钉钉群里和你沟通了

**Comment by ineo6** [comment]
@Chillimeat 如果还有问题，简单描述下你的配置。
@ainuoyan thanks 👍

**Comment by ainuoyan** [comment]
> @Chillimeat 如果还有问题，简单描述下你的配置。
> 
> @ainuoyan thanks 👍

我看到这个Issues的邮件后就看到钉钉机器人群里有人在问这个问题，我猜是同一个人😂

**Comment by Chillimeat** [comment]
@ainuoyan @ineo6 感谢两位支持呀

**Comment by ineo6** [comment]
已解决
