### ISSUE TITLE
考虑过增加 webhook 支持吗？

### ISSUE THREAD

**Issue by Chillimeat** [ineo6/hubot-dingtalk#7]
考虑过增加 webhook 支持吗？

**Comment by ineo6** [comment]
有这样的计划，目前还没有开发。顺便问下，你的使用场景是？

**Comment by ineo6** [comment]
目前方案如下，不知道实际的使用需求是怎么样的。

## 1. 首先需要配置群组

添加`dingtalk-room.json`配置文件：

```json
[
  {
    "room": "room1",
    "env": "HUBOT_DINGTALK_ACCESS_TOKEN"
  },
  {
    "room": "room2",
    "env": "HUBOT_DINGTALK_ACCESS_TOKEN2"
  }
]
```

`env`指向环境变量的名称。

## 2. 发送消息

```js
robot.messageRoom('room1', "response")
```

**Comment by Chillimeat** [comment]
> 目前方案如下，不知道实际的使用需求是怎么样的。
> 
> ## 1. 首先需要配置群组
> 添加`dingtalk-room.json`配置文件：
> 
> ```json
> [
>   {
>     "room": "room1",
>     "env": "HUBOT_DINGTALK_ACCESS_TOKEN"
>   },
>   {
>     "room": "room2",
>     "env": "HUBOT_DINGTALK_ACCESS_TOKEN2"
>   }
> ]
> ```
> 
> `env`指向环境变量的名称。
> 
> ## 2. 发送消息
> ```js
> robot.messageRoom('room1', "response")
> ```

感谢回复，我的场景是我希望把报警信息或者一些需要用户处理的信息，通过 dinghubot 发给钉钉

**Comment by ineo6** [comment]
`1.5.0`版本已添加

**Comment by Chillimeat** [comment]
感谢呀 ，我还想着自己加上去呢
